#!/bin/python3

import subprocess
from ast import literal_eval
from inginious import feedback, rst, input
from utils import bgp_utils as bgp
from utils import inginious_utils as utils
from inginious.vm import vm_utils

grade = 0
nprob = 3
inc = 100/nprob

# We create the python script based on the text file describing the network
ases, shuffled = bgp.parse_bgp_file("public/network", "scripts/bgp.py")

# Upload the network_manager file, containing useful method for simple bgp networks
vm_utils.upload_file("scripts/network_manager.py")

# We execute the script on the virtual machine and retrieve the RIBs of all ASes
ribs = bgp.get_ribs("scripts/bgp.py")

# We get the answer of the student
q1 = utils.get_single_line_answer("q1")
# The answer retrieved above is based on a shuffled version of the network that
# was run on the VM. We have to "deshuffle" the answer of the student before
# comparing it with the RIBs retrieved before
bgp.deshuffle_answer(q1, ases, shuffled)
# ases[4] corresponds to AS5, so ribs[ases[4].asn] get the value of the key "as5",
# which is the RIB of AS5
if bgp.compare_known_prefixes(q1, ribs[ases[4].asn]):
    utils.set_problem_result("q1", "success", "Correct")
    grade += inc
else:
    utils.set_problem_result("q1", "failed", "Your answer is not correct")
    
q2 = utils.get_single_line_answer("q2")
bgp.deshuffle_answer(q2, ases, shuffled)
if bgp.compare_best_route(q2, ribs[ases[4].asn], ases[3].prefix):
    utils.set_problem_result("q2", "success", "Correct")
    grade += inc
else:
    utils.set_problem_result("q2", "failed", "Your answer is not correct") 
    
q3 = utils.get_multiple_line_answer("q3")
bgp.deshuffle_answer(q3, ases, shuffled)
if bgp.compare_all_routes(q3, ribs[ases[4].asn], ases[3].prefix):
    utils.set_problem_result("q3", "success", "Correct")
    grade += inc
else:
    utils.set_problem_result("q3", "failed", "Your answer is not correct") 
                   
feedback.set_grade(grade) 
if grade >= 50:
    feedback.set_global_result("success")
else:
    feedback.set_global_result("failed")