#!/bin/python3
# -*- coding: utf-8 -*-
#
# This file is part of INGInious. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.

import sys
import subprocess
from ast import literal_eval

def error(msg):
	print("Error => " + msg)
	exit(255)

def upload_file(file):
	r = subprocess.run(["/bin/upload-to-vm", file], stdout=subprocess.PIPE)
	if r.returncode != 0:
		error("Unable to send the file {} to the VM.".format(file))

def get_ribs(file):
	r = subprocess.run(["/bin/execute-in-vm", "python {}".format(file)], 
			   stdout=subprocess.PIPE)
	if r.returncode != 0:
		error("Unable to execute the file " + file)
	return r.stdout.decode("utf-8")


if len(sys.argv) < 2:
	error("Wrong number of arguments.\nUsage: $ ./get_bgp_rib file [as]")
upload_file(sys.argv[1])
filename = sys.argv[1][sys.argv[1].rfind('/')+1:]
out = get_ribs(filename)
if "Error" in out:
	error("Failed to retrieve the ribbs of the network describe in " + file)

if(len(sys.argv) == 2):
	print(out)
else:
	ribs = literal_eval(out)
	print(ribs[sys.argv[2]])