#!/bin/bash
# -*- coding: utf-8 -*-
#
# This file is part of INGInious. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.

if [[ $# -ne 1 ]]; then
    echo "Illegal number of parameters"
    exit 255
fi

SSH_EXIT_STATUS=255
while [[ $SSH_EXIT_STATUS -eq 255 ]];do
    ssh -p 20002 -i /add/ssh/id_rsa root@localhost $1 2> /dev/null
    SSH_EXIT_STATUS=$?
done